name: 'Send log to Loki'
description: 'A GitHub Action to send log to Loki'
inputs:
  measurement:
    description: 'Controls the measurement type; "start" to record the start time of the job, "finish" or undefined to send the log message to Loki'
  status:
    description: 'Controls the status of the log message; "success" or "failure"'
  loki_address:
    description: 'Loki server address required to send log'
  loki_username:
    description: 'Loki username required to send log'
  loki_password:
    description: 'Loki password required to send log'
  additional_labels:
    description: 'Additional labels to be added to the log in logfmt format'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'send'
  color: 'yellow'
