name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true
        default: "v1.0.0"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start time
        uses: ./
        with:
          measurement: start

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Update version in package.json, README.md, and index.js
        run: |
          tag=${{ github.event.inputs.tag }}
          sed -i "s/\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/\"version\": \"$tag\"/g" package.json
          sed -i "s/shinto-labs\/send-log-to-loki@v[0-9]\+\.[0-9]\+\.[0-9]\+/shinto-labs\/send-log-to-loki@$tag/g" README.md
          sed -i "s/shinto-labs\/send-log-to-loki@v[0-9]\+\.[0-9]\+\.[0-9]\+/shinto-labs\/send-log-to-loki@$tag/g" index.js

      - name: Update version in README.md
        run: |
          tag=${{ github.event.inputs.tag }}
          sed -i "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/v$tag/g" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist package.json README.md index.js
          git commit -m 'Build action with ncc'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a tag and push
        run: |
          git tag ${{ github.event.inputs.tag }}
          git push origin main ${{ github.event.inputs.tag }}

      - name: Send Log to Loki
        uses: ./
        with:
          loki_address: "http://your-loki-instance:3100"
          loki_username: ${{ secrets.LOKI_USERNAME }}
          loki_password: ${{ secrets.LOKI_PASSWORD }}
          status: ${{ job.status }}
          additional_labels: "example_label=example_value"
